#pragma once
#include "Processor.h"
#include "BinaryData.h"
class RadioKnob final:public juce::Slider{public:float visualPosition=0;};
class RadioLook final:public juce::LookAndFeel_V4{
public:
 void drawRotarySlider(juce::Graphics& g,int x,int y,int w,int h,float,float start,float end,juce::Slider& s)override{auto& k=static_cast<RadioKnob&>(s);auto b=juce::Rectangle<float>(float(x),float(y),float(w),float(h)).reduced(3);const float d=juce::jmin(b.getWidth(),b.getHeight()),cx=b.getCentreX(),cy=b.getCentreY(),r=d*.5f,angle=start+k.visualPosition*(end-start);juce::ColourGradient grad(juce::Colour(0xff373733),cx-r,cy-r,juce::Colour(0xff070706),cx+r,cy+r,false);g.setGradientFill(grad);g.fillEllipse(cx-r,cy-r,d,d);g.setColour(juce::Colour(0xff8a806d));g.drawEllipse(cx-r,cy-r,d,d,2);g.setColour(juce::Colour(0xfff5d89f));g.drawLine(cx+std::sin(angle)*r*.35f,cy-std::cos(angle)*r*.35f,cx+std::sin(angle)*r*.78f,cy-std::cos(angle)*r*.78f,juce::jmax(2.f,d*.025f));}
 void drawToggleButton(juce::Graphics&,juce::ToggleButton&,bool,bool)override{}
};
class RadioBoxEditor final:public juce::AudioProcessorEditor,private juce::Timer{
 RadioBoxProcessor& processor;RadioLook look;
 std::array<juce::Image,3> panels{juce::ImageCache::getFromMemory(BinaryData::RadioBoxOlive_jpeg,BinaryData::RadioBoxOlive_jpegSize),juce::ImageCache::getFromMemory(BinaryData::RadioBoxRed_jpeg,BinaryData::RadioBoxRed_jpegSize),juce::ImageCache::getFromMemory(BinaryData::RadioBoxBlue_jpeg,BinaryData::RadioBoxBlue_jpegSize)};
 juce::ComboBox station,theme;juce::TextButton previous{"<"},next{">"};std::array<RadioKnob,10> knobs;std::array<juce::Label,10> values;std::array<juce::ToggleButton,6> toggles;
 using SA=juce::AudioProcessorValueTreeState::SliderAttachment;using BA=juce::AudioProcessorValueTreeState::ButtonAttachment;std::array<std::unique_ptr<SA>,10> sliderAttachments;std::array<std::unique_ptr<BA>,3> toggleAttachments;std::unique_ptr<BA> dropoutAttachment,powerAttachment,lightAttachment;std::unique_ptr<juce::AudioProcessorValueTreeState::ComboBoxAttachment> themeAttachment;
 int themeIndex=0;float level=0;static constexpr std::array<const char*,10> knobIDs{"loRoll","midEq","hiRoll","bandwidth","tuning","filter","drive","tone","width","mix"};
 static constexpr std::array<juce::Rectangle<int>,10> knobBounds{{{126,199,89,89},{246,199,89,89},{369,199,89,89},{224,363,124,124},{626,525,282,282},{1103,194,96,96},{1288,194,96,96},{1098,378,106,106},{995,603,100,100},{1191,603,100,100}}};
 juce::Rectangle<int> scaled(juce::Rectangle<int> b)const{float s=float(getWidth())/1536;return b.toFloat().transformedBy(juce::AffineTransform::scale(s)).toNearestInt();}
 float raw(const char* id)const{return processor.state.getRawParameterValue(id)->load();}
 void timerCallback()override{refresh(1.f/60);}
 juce::String valueText(size_t i,float v)const{if(i==0||i==2)return juce::String(int(v))+" Hz";if(i==1)return juce::String(v,1)+" dB";if(i==4)return juce::String(int(v));if(i==7)return v<-.05f?"DARK":v>.05f?"BRIGHT":"CENTER";if(i==8)return juce::String(int(v))+"%";return juce::String(int(v))+"%";}
public:
 explicit RadioBoxEditor(RadioBoxProcessor& p):AudioProcessorEditor(p),processor(p){setLookAndFeel(&look);
  auto style=[this](juce::ComboBox& c){c.setColour(juce::ComboBox::backgroundColourId,juce::Colour(0xee171613));c.setColour(juce::ComboBox::textColourId,juce::Colour(0xffffdc94));c.setColour(juce::ComboBox::outlineColourId,juce::Colour(0xffaa7740));addAndMakeVisible(c);};style(station);style(theme);station.setComponentID("preset.selector");theme.setComponentID("theme.selector");for(int i=0;i<10;++i)station.addItem(havi::presetNames[size_t(i)],i+1);theme.addItemList({"Olive Green","Gold","Red","Burgundy","Blue"},1);station.onChange=[this]{processor.selectPreset(station.getSelectedId()-1);refresh(0);};previous.onClick=[this]{processor.selectPreset((processor.getCurrentProgram()+9)%10);refresh(0);};next.onClick=[this]{processor.selectPreset((processor.getCurrentProgram()+1)%10);refresh(0);};for(auto* b:{&previous,&next}){b->setColour(juce::TextButton::buttonColourId,juce::Colour(0xff28231c));b->setColour(juce::TextButton::textColourOffId,juce::Colour(0xffffd898));addAndMakeVisible(b);}previous.setComponentID("preset.previous");next.setComponentID("preset.next");themeAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(p.state,"theme",theme);
  for(size_t i=0;i<knobs.size();++i){auto& k=knobs[i];k.setComponentID(juce::String("knob.")+knobIDs[i]);k.setSliderStyle(juce::Slider::RotaryVerticalDrag);k.setTextBoxStyle(juce::Slider::NoTextBox,false,0,0);k.setRotaryParameters(juce::MathConstants<float>::pi*1.25f,juce::MathConstants<float>::pi*2.75f,true);k.setPopupDisplayEnabled(true,true,this);k.setMouseDragSensitivity(i==4?300:180);addAndMakeVisible(k);sliderAttachments[i]=std::make_unique<SA>(p.state,knobIDs[i],k);k.visualPosition=p.state.getParameter(knobIDs[i])->convertTo0to1(raw(knobIDs[i]));values[i].setJustificationType(juce::Justification::centred);values[i].setColour(juce::Label::textColourId,juce::Colour(0xffffdfa3));values[i].setColour(juce::Label::backgroundColourId,juce::Colour(0xcc11100e));addAndMakeVisible(values[i]);}
  const char* ids[]={"am","fm","sw"};for(int i=0;i<3;++i){toggles[size_t(i)].setComponentID(juce::String("switch.")+ids[i]);toggles[size_t(i)].onClick=[this,i]{if(toggles[size_t(i)].getToggleState())processor.selectBand(i);else processor.selectBand((i+1)%3);};addAndMakeVisible(toggles[size_t(i)]);}
  toggles[3].setComponentID("switch.dropout");toggles[4].setComponentID("switch.power");toggles[5].setComponentID("switch.vuLight");for(int i=3;i<6;++i)addAndMakeVisible(toggles[size_t(i)]);dropoutAttachment=std::make_unique<BA>(p.state,"dropout",toggles[3]);powerAttachment=std::make_unique<BA>(p.state,"power",toggles[4]);lightAttachment=std::make_unique<BA>(p.state,"vuLight",toggles[5]);
  setResizable(true,true);getConstrainer()->setFixedAspectRatio(1536.0/858.0);setResizeLimits(960,536,1536,858);setSize(1200,670);refresh(0);startTimerHz(60);
 }
 ~RadioBoxEditor()override{stopTimer();setLookAndFeel(nullptr);}
 void refresh(float seconds){themeIndex=juce::jlimit(0,4,int(raw("theme")));station.setSelectedId(processor.getCurrentProgram()+1,juce::dontSendNotification);theme.setSelectedId(themeIndex+1,juce::dontSendNotification);for(size_t i=0;i<knobs.size();++i){float v=raw(knobIDs[i]);knobs[i].setValue(v,juce::dontSendNotification);float target=processor.state.getParameter(knobIDs[i])->convertTo0to1(v);knobs[i].visualPosition=havi::visualStep(knobs[i].visualPosition,target,seconds);values[i].setText(valueText(i,v),juce::dontSendNotification);}for(int i=0;i<3;++i)toggles[size_t(i)].setToggleState(raw(havi::controlIDs[size_t(11+i)])>.5f,juce::dontSendNotification);if(seconds>0)level=havi::Meter::animate(level,processor.meter.take(),seconds);repaint();}
 float meterValue()const{return level;}
 void paint(juce::Graphics& g)override{juce::Graphics::ScopedSaveState save(g);float s=float(getWidth())/1536;g.addTransform(juce::AffineTransform::scale(s));int source=themeIndex==2||themeIndex==3?1:themeIndex==4?2:0;g.drawImage(panels[size_t(source)],juce::Rectangle<float>(0,0,1536,858));if(themeIndex==1){g.setColour(juce::Colour(0x35d79328));g.fillRect(0,47,1536,811);}if(themeIndex==3){g.setColour(juce::Colour(0x421f000c));g.fillRect(0,47,1536,811);}
  const bool lit=raw("vuLight")>.5f;if(!lit){g.setColour(juce::Colour(0x8a181713));g.fillRoundedRectangle(546,171,471,286,55);}else{g.setColour(juce::Colour(0x22ffb43c));g.fillRoundedRectangle(546,171,471,286,55);}
  const juce::Point<float> pivot(768,429);const float angle=(-58+116*std::clamp(level,0.f,1.f))*juce::MathConstants<float>::pi/180;g.setColour(juce::Colour(0xff6f1d26));g.drawLine(pivot.x,pivot.y,pivot.x+std::sin(angle)*195,pivot.y-std::cos(angle)*195,8);g.fillEllipse(pivot.x-13,pivot.y-13,26,26);
  auto lamp=[&](float x,float y,float r,juce::Colour c,bool on){g.setColour(on?c.withAlpha(.30f):juce::Colours::black.withAlpha(.45f));g.fillEllipse(x-r*1.6f,y-r*1.6f,r*3.2f,r*3.2f);g.setColour(on?c:juce::Colour(0xff321e18));g.fillEllipse(x-r,y-r,r*2,r*2);};lamp(675,411,10,juce::Colour(0xff65ff28),level>.045f);lamp(859,411,10,juce::Colour(0xffff251a),processor.overload.load());lamp(1056,316,14,juce::Colour(0xffffa22a),lit);
  for(int i=0;i<3;++i)if(raw(havi::controlIDs[size_t(11+i)])>.5f){g.setColour(juce::Colour(0x55ff9f24));g.fillRoundedRectangle(float(164+i*88),596,78,130,8);}
  const bool drop=raw("dropout")>.5f,power=raw("power")>.5f;lamp(519,650,8,juce::Colour(0xffffa52e),drop);lamp(1388,658,15,juce::Colour(0xffff2a16),!power);lamp(1341,443,8,juce::Colour(0xffffb03a),power);g.setColour(juce::Colour(0xfff3d79e));g.setFont(13.f);g.drawText("BY UOC SOUND",657,117,220,18,juce::Justification::centred);
 }
 void resized()override{previous.setBounds(scaled({300,8,32,32}));station.setBounds(scaled({341,7,205,34}));next.setBounds(scaled({553,8,32,32}));theme.setBounds(scaled({985,7,205,34}));for(size_t i=0;i<knobs.size();++i)knobs[i].setBounds(scaled(knobBounds[i]));const std::array<juce::Rectangle<int>,10> vb{{{115,293,110,21},{238,293,105,21},{360,293,110,21},{233,491,106,21},{713,797,110,21},{1095,295,112,21},{1280,295,112,21},{1092,488,118,21},{978,707,132,21},{1178,707,128,21}}};for(size_t i=0;i<values.size();++i){values[i].setBounds(scaled(vb[i]));values[i].setFont(11.f*float(getWidth())/1200);}toggles[0].setBounds(scaled({157,587,87,147}));toggles[1].setBounds(scaled({245,587,87,147}));toggles[2].setBounds(scaled({333,587,87,147}));toggles[3].setBounds(scaled({486,596,67,139}));toggles[4].setBounds(scaled({1305,378,78,134}));toggles[5].setBounds(scaled({1026,274,62,84}));}
};
